### ISSUE TITLE
About the datasets

### ISSUE THREAD

**Issue by ke-ke9** [wuch15/EMNLP2019-NRMS#1]
Could you provide the datasets please? Thank you so much.

**Comment by w-zm** [comment]
> Could you provide the datasets please? Thank you so much.

Hi，hava you found the datasets?

**Comment by wuch15** [comment]
Please use our larger public dataset here: https://msnews.github.io/

**Comment by shengyuzhang** [comment]
@wuch15 请问可以提供和代码一致的原始数据的几个样本吗？目的是想用来看下代码里面的一些变量内容以调整为public dataset可用的代码形式。这个public dataset 目前不可以直接跑。具体而言，我对这两个地方的变量内容不太了解：
alldoc=[newsindex[x] for x in userline[2].split('#TAB#')[0].split()]
test_session_data.append([userline[0],userline[2].split('#TAB#')[0].split(),userline[2].split('#TAB#')[1]])
感谢🙏

**Comment by wuch15** [comment]
对于public dataset，这块的code需要更改一下：

for user in trainuser:
    userline=user.replace('\n','').split('\t')
    clickids=[newsindex[x] for x in userline[3].split()][-50:]
    pdoc=[newsindex[x.split('-')[0]] for x in userline[4].split() if x.split('-')[1]=='1']
    ndoc=[newsindex[x.split('-')[0]] for x in userline[4].split() if x.split('-')[1]=='0']
    for doc in pdoc:
        negd=newsample(ndoc,npratio)
        negd.append(doc)
        candidate_label=[0]*npratio+[1]
        candidate_order=list(range(npratio+1))
        random.shuffle(candidate_order)
        candidate_shuffle=[]
        candidate_label_shuffle=[]
        for i in candidate_order:
            candidate_shuffle.append(negd[i])
            candidate_label_shuffle.append(candidate_label[i])
        train_candidate.append(candidate_shuffle)
        train_label.append(candidate_label_shuffle)
        train_user_his.append(clickids+[0]*(50-len(clickids))) 


for user in testuser:
    userline=user.replace('\n','').split('\t')
    clickids=[newsindex[x] for x in userline[3].split()][-50:]
    doc=[newsindex[x.split('-')[0]] for x in userline[4].split()]
    index=[]
    index.append(len(test_candidate))
    test_user_his.append(clickids+[0]*(50-len(clickids)))
    for doc in doc:
        test_candidate.append(doc)
    index.append(len(test_candidate))
    test_index.append(index)

**Comment by shengyuzhang** [comment]
感谢！🙏

**Comment by shengyuzhang** [comment]
请问，如果想要和论文中的实验结果可比，是使用全量还是small的数据集呢？还是说数据差异比较大，没法和公开集直接对比呢？

**Comment by wuch15** [comment]
你好，最好直接和MIND数据集中的NRMS结果进行对比。

**Comment by shengyuzhang** [comment]
> 你好，最好直接和MIND数据集论文中的NRMS结果进行对比。

哦哦明白，感谢🙏
